version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net
  kafka:
    container_name: "kafka"
    image: confluentinc/cp-kafka:5.4.3
    ports:
      - '9092:9092'
      - '9093:9093'
      - '29092:29092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  server:
    container_name: "server"
    build: server/
    depends_on:
      - kafka
    networks:
      - kafka-net
    ports:
      - '8080:8080'
    environment:
      - KAFKA_HOST=kafka:29092

  client:
    container_name: "client"
    build: client/
    depends_on:
      - kafka
      - postgres
    networks:
      - kafka-net
    environment:
      - KAFKA_HOST=kafka:29092
      - PG_HOST=postgres:5432
      - PG_PASSWORD=postgres
      - PG_USERNAME=postgres

  postgres:
    image: postgres:13.3
    container_name: "postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge